#
# Makefile for the AXI4 drivers.
#

obj-$(CONFIG_MWGENERIC_OF) += mwgeneric_of.o

mwgeneric_of-objs = mwgeneric_of_src.o mwgeneric_common.o

obj-$(CONFIG_MWGENERIC_PCI) += mwgeneric_pci.o

mwgeneric_pci-objs = mwgeneric_pci_src.o mwgeneric_common.o
